# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['app.py'],
    pathex=['c:\\Users\\WARER\\Desktop\\projects\\internet'],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('al-nazim-icon.svg', '.'),
        ('.env', '.'),
        ('billing_system', 'billing_system'),
        ('snmp_monitor', 'snmp_monitor'),
        ('mikrotik_api', 'mikrotik_api'),
        ('network_tools', 'network_tools'),
        ('api_gateway', 'api_gateway'),
    ],
    hiddenimports=[
        'auth',
        'database',
        'turso_db',
        'billing_system',
        'billing_system.billing_logic',
        'billing_system.database',
        'billing_system.config',
        'billing_system.mikrotik_sync',
        'billing_system.sync_engine',
        'snmp_monitor',
        'snmp_monitor.agent',
        'snmp_monitor.config',
        'snmp_monitor.signal_monitor',
        'snmp_monitor.signal_scanner',
        'mikrotik_api',
        'mikrotik_api.config',
        'mikrotik_api.mikrotik_manager',
        'mikrotik_api.auto_mapper',
        'network_tools',
        'network_tools.ping',
        'api_gateway',
        'api_gateway.main',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Al-Nathim',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)